package com.example.rocketjournal.model.dataModel

import kotlinx.serialization.Serializable

@Serializable
data class ListData(
    val listId: Int? = null, // Auto-generated by the database
    val userId: Int,
    val name: String
)